### ISSUE TITLE
OCB-specific README in GitHub

### ISSUE THREAD

**Issue by COLABORATI** [OCA/OCB#381] opened 2015-11-16 15:50 UTC
Unfortunately the website https://odoo-community.org/ has a lot of marketing-style non-content to offer, but does not explain what exactly are the goals and the differences of the code in this repo. Please give a clear explanation about this, thank you!

**Comment by pedrobaeza** [comment] 2015-11-16 15:59
If you have any improvement to suggest, please provide it as a PR. Meanwhile, the brief description here drafts the scope: https://odoo-community.org/project/backport-maintainers-17

**Comment by COLABORATI** [comment] 2015-11-16 16:06
Interesting answer, thank you for this deep insight into how this community works. 
Why don't you just put that linked description on top of the readme? 
You want a PR for this? Common...

**Comment by pedrobaeza** [comment] 2015-11-16 16:10
It should be good, but we prefer to not touch it for now because that README is copied directly from upstream Odoo, causing possible conflicts in case they change it. Anyway, you mention https://odoo-community.org, and that page belongs to there, so the problem is not here. We are studying improving visibility of pages, but everything is there, although you consider it marketing material.

**Comment by StefanRijnhart** [comment] 2015-11-24 06:16
@colaborati I think it is a great idea to adapt the README of this project to reflect the changes compared to upstream Odoo. I also think it is a great idea if someone files a PR for that. Reopening this issue to track progress and other opinions on changing the README.

**Comment by dreispt** [comment] 2015-11-24 09:32
I agree with @pedrobaeza in that we should avoid changing the upstream README.
I suggest to instead create a `README-Backports.md`.

**Comment by StefanRijnhart** [comment] 2015-11-24 10:15
Can we point GitHub to show the alternative README in the branch by
default? Otherwise adding it may not be a very useful excercise.

**Comment by StefanRijnhart** [comment] 2016-04-06 17:09
Closing this because there is no pull request and no further discussion.

**Closed as completed by StefanRijnhart** 2016-04-06 17:09 UTC
Labels: enhancement
