### ISSUE TITLE
 Undefined variable: "$o-chatter-min-width".         on line 16087 of stdin, in mixin `@content`

### ISSUE THREAD

**Issue by digitalliuzg** [OCA/OCB#934] opened 2020-06-26 10:20 UTC
Impacted versions:13

Steps to reproduce:install  Enterprise All modules  except web_enterprise

Current behavior:2020-06-26 10:06:21,775 37276 WARNING ERP_DEMO_C03 odoo.addons.base.models.assetsbundle: Error: Undefined variable: "$o-chatter-min-width".
        on line 16087 of stdin, in mixin `@content`
        from line 62 of e:/dvt/drissuite13_win_v3/source/addons/web/static/lib/bootstrap/scss/mixins/_breakpoints.scss, in mixin `media-breakpoi
nt-up`
        from line 16082 of stdin
>>             width: $o-chatter-min-width;
   -------------------^
This error occured while compiling the bundle 'web.assets_backend' containing:
    - /web/static/lib/bootstrap/scss/_functions.scss
    - /web/static/lib/bootstrap/scss/_mixins.scss
    - /web/static/src/scss/bs_mixins_overrides.scss
    - /web/static/src/scss/utils.scss
    - /web/static/src/scss/primary_variables.scss
    - /web_editor/static/src/scss/web_editor.variables.scss
    - /mail/static/src/scss/variables.scss
    - /portal/static/src/scss/primary_variables.scss
    - /website/static/src/scss/primary_variables.scss
    - /website/static/src/scss/options/user_values.scss
    - /website/static/src/scss/options/colors/user_color_palette.scss
    - /website/static/src/scss/options/colors/user_theme_color_palette.scss
    - /website_sale/static/src/scss/primary_variables.scss
    - /account/static/src/scss/variables.scss
    - /hr_org_chart/static/src/scss/variables.scss
    - /marketing_automation/static/src/scss/variables.scss
    - /website_blog/static/src/scss/primary_variables.scss
    - /website/static/src/scss/secondary_variables.scss
    - /web_editor/static/src/scss/secondary_variables.scss
    - /web/static/src/scss/secondary_variables.scss
    - /web_editor/static/src/scss/bootstrap_overridden_backend.scss
    - /web_editor/static/src/scss/bootstrap_overridden.scss
    - /web/static/src/scss/bootstrap_overridden.scss
    - /web/static/lib/bootstrap/scss/_variables.scss
    - /web/static/src/scss/import_bootstrap.scss
    - /web/static/src/scss/bootstrap_review.scss
    - /web/static/src/scss/webclient_extra.scss
    - /web/static/src/scss/webclient_layout.scss
    - /web/static/src/scss/webclient.scss
    - /web/static/src/scss/domain_selector.scss
    - /web/static/src/scss/model_field_selector.scss
    - /web/static/src/scss/progress_bar.scss
    - /web/static/src/scss/dropdown.scss
    - /web/static/src/scss/dropdown_extra.scss
    - /web/static/src/scss/tooltip.scss
    - /web/static/src/scss/switch_company_menu.scss
    - /web/static/src/scss/debug_manager.scss
    - /web/static/src/scss/control_panel.scss
    - /web/static/src/scss/fields.scss
    - /web/static/src/scss/fields_extra.scss
    - /web/static/src/scss/views.scss
    - /web/static/src/scss/pivot_view.scss
    - /web/static/src/scss/graph_view.scss
    - /web/static/src/scss/form_view.scss
    - /web/static/src/scss/form_view_extra.scss
    - /web/static/src/scss/list_view.scss
    - /web/static/src/scss/list_view_extra.scss
    - /web/static/src/scss/kanban_dashboard.scss
    - /web/static/src/scss/kanban_examples_dialog.scss
    - /web/static/src/scss/kanban_column_progressbar.scss
    - /web/static/src/scss/kanban_view.scss
    - /web/static/src/scss/kanban_view_mobile.scss
    - /web/static/src/scss/web_calendar.scss
    - /web/static/src/scss/web_calendar_mobile.scss
    - /web/static/src/scss/search_view.scss
    - /web/static/src/scss/search_panel.scss
    - /web/static/src/scss/search_view_mobile.scss
    - /web/static/src/scss/dropdown_menu.scss
    - /web/static/src/scss/search_view_extra.scss
    - /web/static/src/scss/data_export.scss
    - /base/static/src/scss/onboarding.scss
    - /web/static/src/scss/attachment_preview.scss
    - /web/static/src/scss/notification.scss
    - /web/static/src/scss/base_document_layout.scss
    - /web/static/src/scss/ribbon.scss
    - /web/static/src/scss/base_settings.scss
    - /web/static/src/scss/report_backend.scss
    - /web_mobile/static/src/scss/mobile.scss
    - /web_mobile/static/src/scss/pivot_view_mobile.scss
    - /base_import/static/src/scss/base_import.scss
    - /web_cohort/static/src/scss/web_cohort.scss
    - /web_diagram/static/src/scss/diagram_view.scss
    - /web_editor/static/src/scss/web_editor.common.scss
    - /web_editor/static/src/scss/web_editor.backend.scss
    - /web_gantt/static/src/scss/web_gantt.scss
    - /web_grid/static/src/scss/grid_view.scss
    - /base_setup/static/src/scss/settings.scss
    - /mail/static/src/scss/announcement.scss
    - /mail/static/src/scss/discuss.scss
    - /mail/static/src/scss/abstract_thread_window.scss
    - /mail/static/src/scss/thread_window.scss
    - /mail/static/src/scss/composer.scss
    - /mail/static/src/scss/chatter.scss
    - /mail/static/src/scss/followers.scss
    - /mail/static/src/scss/thread.scss
    - /mail/static/src/scss/systray.scss
    - /mail/static/src/scss/mail_activity.scss
    - /mail/static/src/scss/activity_view.scss
    - /mail/static/src/scss/kanban_view.scss
    - /mail/static/src/scss/attachment_box.scss
    - /web_map/static/src/scss/mapview.scss
    - /partner_autocomplete/static/src/scss/partner_autocomplete.scss
    - /snailmail/static/src/scss/thread.scss
    - /web_responsive/static/src/css/web_responsive.scss
    - /sms/static/src/scss/thread.scss
    - /resource/static/src/scss/section_backend.scss
    - /utm/static/src/scss/utm_views.scss
    - /web_dashboard/static/src/scss/dashboard_view.scss
    - /calendar/static/src/scss/calendar.scss
    - /sales_team/static/src/scss/sales_team_dashboard.scss
    - /stock/static/src/scss/stock_traceability_report.scss
    - /mrp/static/src/scss/mrp_workorder_kanban.scss
    - /stock_enterprise/static/src/scss/report_stock_quantity.scss
    - /website/static/src/scss/website.backend.scss
    - /website/static/src/scss/website_visitor_views.scss
    - /website_calendar/static/src/scss/appointment_employee_url.scss
    - /website_livechat/static/src/scss/mail_thread_visitor_info.scss
    - /account/static/src/scss/account_reconciliation.scss
    - /account/static/src/scss/account_journal_dashboard.scss
    - /account/static/src/scss/account_dashboard.scss
    - /account/static/src/scss/account_searchpanel.scss
    - /account/static/src/scss/section_and_note_backend.scss
    - /account/static/src/scss/account_activity.scss
    - /project/static/src/scss/project_dashboard.scss
    - /website_theme_install/static/src/scss/website_theme_install.scss
    - /account_online_sync/static/src/scss/online_sync.scss
    - /payment/static/src/scss/payment_acquirer.scss
    - /mail_enterprise/static/src/scss/mail_enterprise.scss
    - /mail_enterprise/static/src/scss/mail_enterprise_mobile.scss
    - /note/static/src/scss/note.scss
    - /hr/static/src/scss/hr.scss
    - /hr_contract/static/src/scss/state_selection.scss
    - /hr_contract/static/src/scss/calendar_mismatch.scss
    - /hr_holidays/static/scss/hr_leave_mobile.scss
    - /hr_holidays/static/src/scss/time_off.scss
    - /hr_org_chart/static/src/scss/hr_org_chart.scss
    - /account_accountant/static/src/scss/move_line_list_view.scss
    - /account_invoice_extract/static/src/scss/account_invoice_extract.scss
    - /account_reports/static/src/scss/account_financial_report.scss
    - /point_of_sale/static/src/scss/pos_dashboard.scss
    - /sale/static/src/scss/sale_onboarding.scss
    - /sale/static/src/scss/product_configurator.scss
    - /account_asset/static/src/scss/account_asset.scss
    - /account_reports/static/src/scss/account_financial_report.scss
    - /sale_enterprise/static/src/scss/sale_enterprise.scss
    - /hr_attendance/static/src/scss/hr_attendance.scss
    - /quality/static/src/scss/tablet_view.scss
    - /helpdesk/static/src/scss/helpdesk.scss
    - /mrp_plm/static/src/scss/mrp_plm_dashboard.scss
    - /quality_control/static/src/scss/quality_dashboard.scss
    - /website_sale/static/src/scss/website_sale_dashboard.scss
    - /website_sale/static/src/scss/website_sale_backend.scss
    - /board/static/src/scss/dashboard.scss
    - /hr_recruitment/static/src/scss/hr_job.scss
    - /hr_referral/static/src/scss/referral_kanban_view.scss
    - /hr_referral/static/src/scss/_fonts.scss
    - /hr_referral/static/src/scss/hr_referral.scss
    - /hr_referral/static/src/scss/hr_onboarding.scss
    - /hr_referral/static/src/scss/progress_bar.scss
    - /account_consolidation/static/src/scss/consolidation_grid_view.scss
    - /account_consolidation/static/src/scss/consolidation_kanban.scss
    - /mass_mailing/static/src/scss/mass_mailing.scss
    - /mass_mailing/static/src/scss/mass_mailing_mobile.scss
    - /hr_skills/static/src/css/hr_skills.scss
    - /marketing_automation/static/src/scss/marketing_automation.scss
    - /planning/static/src/scss/field_colorpicker.scss
    - /project_timesheet_synchro/static/src/scss/project_timesheet_backend.scss
    - /sale_timesheet/static/src/scss/sale_timesheet.scss
    - /gamification/static/src/scss/gamification.scss
    - /social/static/src/scss/social.scss
    - /social_facebook/static/src/scss/social_facebook.scss
    - /social_linkedin/static/src/scss/social_linkedin.scss
    - /social_twitter/static/src/scss/social_twitter.scss
    - /survey/static/src/scss/survey_views.scss
    - /voip/static/src/scss/call_center_field.scss
    - /voip/static/src/scss/voip.scss
    - /sign/static/src/scss/sign_backend.scss
    - /stock_barcode/static/src/scss/stock_barcode.scss
    - /stock_barcode/static/src/scss/client_action.scss
    - /hr_skills_survey/static/src/scss/hr_skills.scss
    - /social_push_notifications/static/src/scss/social_push_notifications.scss
    - /stock_barcode_mobile/static/src/scss/stock_mobile_barcode.scss
    - /lunch/static/src/scss/lunch_kanban.scss
    - /lunch/static/src/scss/lunch_list.scss
    - /maintenance/static/src/scss/maintenance_team_dashboard.scss
    - /website_slides/static/src/scss/rating_rating_views.scss
    - /website_slides/static/src/scss/slide_views.scss
    - /hr_skills_slides/static/src/scss/hr_skills.scss
    - /im_livechat/static/src/scss/im_livechat_history.scss
    - /im_livechat/static/src/scss/im_livechat_form.scss
    - /event/static/src/scss/event.scss
    - /product_matrix/static/src/scss/product_matrix.scss
    - /mrp_workorder/static/src/scss/tablet_view.scss
    - /documents/static/src/scss/documents_kanban_view.scss
    - /documents/static/src/scss/documents_kanban_view_mobile.scss
    - /documents/static/src/scss/documents_document_viewer.scss
    - /mrp_mps/static/src/scss/client_action.scss

Expected behavior:normal execution 

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/11321237/85847092-72cc4f80-b7d9-11ea-96fc-9b27bca0b43f.png)
![image](https://user-images.githubusercontent.com/11321237/85847176-91324b00-b7d9-11ea-80e2-c80cc2f133cd.png)
![image](https://user-images.githubusercontent.com/11321237/85847253-a7d8a200-b7d9-11ea-88cb-02f36d4c3c1b.png)

**Comment by marcos-mendez** [comment] 2021-08-11 16:49
This also happend to me when installing openworx backend theme for v12

`Error: Undefined variable: "$o-kanban-mobile-empty-height".
        on line 11917 of stdin`
        
        Pleasem notice that this a oca/web issue

**Comment by pedrobaeza** [comment] 2021-08-11 16:55
The problem is then on openworx one. I'm using OCB + web_responsive without that problem. Closing as it's nothing about OCA/OCB.

**Closed as completed by pedrobaeza** 2021-08-11 16:55 UTC

**Comment by marcos-mendez** [comment] 2021-08-11 17:05
@pedrobaeza maybe i miss understand the problem, but notice that the variable requested is not defined by the web_responsive as it is a min-height parameter, in my understanding this should be handle by web_responsive and not by openworx. Im wrong?

`The style compilation failed, see the error below. Your recent actions may be the cause, please try reverting the changes you made.

Error: Undefined variable: "$o-kanban-mobile-empty-height".
        on line 11917 of stdin
>>                     min-height: $o-kanban-mobile-empty-height;
   --------------------------------^
This error occured while compiling the bundle 'web.assets_backend' containing:
    - /web/static/lib/bootstrap/scss/_functions.scss
    - /web/static/lib/bootstrap/scss/_mixins.scss
    - /web/static/src/scss/utils.scss
    - /web/static/src/scss/bs_mixins_overrides.scss
    - /web/static/src/scss/primary_variables.scss
    - /web_editor/static/src/scss/web_editor.variables.scss
    - /mail/static/src/scss/variables.scss
    - /portal/static/src/scss/primary_variables.scss
    - /website/static/src/scss/primary_variables.scss
    - /website/static/src/scss/options/colors/user_color_palette.scss
    - /website/static/src/scss/options/colors/user_theme_color_palette.scss
    - /web/static/src/scss/secondary_variables.scss
    - /website/static/src/scss/secondary_variables.scss
    - /account/static/src/scss/variables.scss
    - /web/static/src/scss/bootstrap_overridden.scss
    - /web_editor/static/src/scss/bootstrap_overridden.scss
    - /web/static/src/scss/import_bootstrap_part1.scss
    - /web/static/src/scss/bs_mixins_overrides.scss
    - /web/static/src/scss/import_bootstrap_part2.scss
    - /web/static/src/scss/bootstrap_review.scss
    - /web/static/src/scss/webclient_extra.scss
    - /web/static/src/scss/webclient_layout.scss
    - /web/static/src/scss/webclient.scss
    - /web/static/src/scss/domain_selector.scss
    - /web/static/src/scss/model_field_selector.scss
    - /web/static/src/scss/progress_bar.scss
    - /web/static/src/scss/dropdown.scss
    - /web/static/src/scss/dropdown_extra.scss
    - /web/static/src/scss/tooltip.scss
    - /web/static/src/scss/debug_manager.scss
    - /web/static/src/scss/control_panel.scss
    - /web/static/src/scss/fields.scss
    - /web/static/src/scss/fields_extra.scss
    - /web/static/src/scss/views.scss
    - /web/static/src/scss/pivot_view.scss
    - /web/static/src/scss/graph_view.scss
    - /web/static/src/scss/form_view.scss
    - /web/static/src/scss/form_view_extra.scss
    - /web/static/src/scss/list_view.scss
    - /web/static/src/scss/list_view_extra.scss
    - /web/static/src/scss/kanban_dashboard.scss
    - /web/static/src/scss/kanban_examples_dialog.scss
    - /web/static/src/scss/kanban_column_progressbar.scss
    - /web/static/src/scss/kanban_view.scss
    - /web/static/src/scss/kanban_view_mobile.scss
    - /web/static/src/scss/web_calendar.scss
    - /web/static/src/scss/search_view.scss
    - /web/static/src/scss/search_view_mobile.scss
    - /web/static/src/scss/dropdown_menu.scss
    - /web/static/src/scss/search_view_extra.scss
    - /web/static/src/scss/data_export.scss
    - /base/static/src/scss/onboarding.scss
    - /web/static/src/scss/base_settings.scss
    - /web/static/src/scss/report_backend.scss
    - /base_import/static/src/scss/base_import.scss
    - /web_diagram/static/src/scss/diagram_view.scss
    - /web_editor/static/src/scss/web_editor.common.scss
    - /web_editor/static/src/scss/web_editor.backend.scss
    - /l10n_br_base/static/src/less/form_view.less
    - /mail/static/src/scss/announcement.scss
    - /mail/static/src/scss/discuss.scss
    - /mail/static/src/scss/abstract_thread_window.scss
    - /mail/static/src/scss/thread_window.scss
    - /mail/static/src/scss/composer.scss
    - /mail/static/src/scss/chatter.scss
    - /mail/static/src/scss/followers.scss
    - /mail/static/src/scss/thread.scss
    - /mail/static/src/scss/systray.scss
    - /mail/static/src/scss/mail_activity.scss
    - /mail/static/src/scss/activity_view.scss
    - /mail/static/src/scss/kanban_view.scss
    - /mail/static/src/scss/attachment_box.scss
    - /partner_autocomplete/static/src/scss/partner_autocomplete.scss
    - /account/static/src/scss/account_reconciliation.scss
    - /account/static/src/scss/account_journal_dashboard.scss
    - /account/static/src/scss/account_dashboard.scss
    - /account/static/src/scss/section_and_note_backend.scss
    - /sales_team/static/src/scss/sales_team_dashboard.scss
    - /sale/static/src/scss/sale_onboarding.scss
    - /sale/static/src/scss/product_configurator.scss
    - /web_widget_x2many_2d_matrix/static/src/scss/web_widget_x2many_2d_matrix.scss
    - /stock/static/src/scss/stock_traceability_report.scss
    - /mrp/static/src/scss/mrp_workorder_kanban.scss
    - /web_responsive/static/src/css/web_responsive.scss
    - /web_responsive/static/src/css/search_view_mobile.scss
    - /web_responsive/static/src/css/kanban_view_mobile.scss
    - /backend_theme_v12/static/src/scss/style.scss
    - /backend_theme_v12/static/src/scss/sidebar.scss
    - /website/static/src/scss/website.backend.scss
    - /website_theme_install/static/src/scss/website_theme_install.scss
    - /web_settings_dashboard/static/src/scss/dashboard.scss`

**Comment by pedrobaeza** [comment] 2021-08-11 17:07
This is not the proper place for this, as this is OCB, but as said, I don't have such problem using web_responsive on v12. If you have the patch clear, you can propose a PR to OCA/web though.

**Comment by pman-jvm** [comment] 2022-07-07 02:19
Halo @digitalliuzg digitalliuzg
