### ISSUE TITLE
[14.0] Point of sale error clicking the lens button

### ISSUE THREAD

**Issue by Mat-moran** [OCA/OCB#1028] opened 2021-07-27 06:54 UTC
Seems that after this commit b350058e6cb70bbf4767fb6af66418be0d45680b the lens button in the POS has been broken.

Impacted versions: 14.0 (I did not check other versions)

Steps to reproduce: 

- Open a POS session,
- create one or two tickets
- click on the `lens button` :

Current behavior:
You get the next error after click on `lens button`.
```
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/custom/src/odoo/addons/web/controllers/main.py", line 1389, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/custom/src/odoo/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/addons/point_of_sale/models/pos_order.py", line 715, in export_for_ui
    return self.mapped(self._export_for_ui) if self else []
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 5241, in mapped
    return self._mapped_func(func)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 5197, in _mapped_func
    vals = [func(rec) for rec in self]
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 5197, in <listcomp>
    vals = [func(rec) for rec in self]
  File "/opt/odoo/custom/src/odoo/addons/pos_hr/models/pos_order.py", line 26, in _export_for_ui
    result = super(PosOrder, self)._export_for_ui(order)
  File "/opt/odoo/custom/src/odoo/addons/point_of_sale/models/pos_order.py", line 689, in _export_for_ui
    'uid': re.search('([0-9]|-){14}', order.pos_reference).group(0),
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AttributeError: 'NoneType' object has no attribute 'group'
```

Expected behavior:

When you click on the lens button you go to a list view with all the orders of this POS to see older tickets and reprint them.

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2021-07-27 06:55
The referred commit has nothing to do with PoS.

**Comment by pedrobaeza** [comment] 2021-07-27 06:56
Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - click on the blue door icon of the version row - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by pedrobaeza** [comment] 2021-07-27 06:56
And if so, please put it on odoo/odoo, not here.

**Closed as completed by pedrobaeza** 2021-07-27 06:56 UTC
