### ISSUE TITLE
Error on creating Invoice Version 11.0

### ISSUE THREAD

**Issue by h3llopy** [OCA/OCB#1026] opened 2021-07-20 10:12 UTC
Impacted versions:
11.0
Steps to reproduce:
Create invoice
Current behavior:
When click create invoice server error pop-up
Expected behavior:
Should be able to create without pop-up error
Video/Screenshot link (optional):

https://www.loom.com/share/50c9767e9d4f46d7a81ab7052488ff44

**Comment by pedrobaeza** [comment] 2021-07-20 11:37
Sorry, this issue tracker is not for this:

- It's only for specific things on OCB branch, not Odoo general thing.
- Version 11 is an obsolete one.
- I'm pretty sure the problem is not reproducible with standard configuration.

Please ask on forums.

Closing due to this.

**Closed as completed by pedrobaeza** 2021-07-20 11:37 UTC
