### ISSUE TITLE
OCB/addons/fetchmail/models/fetchmail.py raises error on handshake

### ISSUE THREAD

**Issue by ferdiga** [OCA/OCB#836] opened 2019-02-27 11:41 UTC
Impacted versions:
odoo12 - docker
Steps to reproduce:
multiple domains for one IP address
Current behavior:
Connection test failed: 1
[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:720)
Expected behavior:
run without error - see
https://stackoverflow.com/questions/53683537/python-error-ssl-ssl-sslerror-ssl-sslv3-alert-handshake-failure-sslv3-alert
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment] 2019-02-27 11:50
Is this something specific of OCB?

**Comment by ferdiga** [comment] 2019-02-27 11:52
probably not, but Odoo in the past Odoo never fixed such things

**Comment by pedrobaeza** [comment] 2019-02-27 11:56
But OCB neither if no patch provided. This is only for hosting patches, not issues, unless specific of OCB (because a regression for example). So I'm afraid I have to close this.

**Closed as completed by pedrobaeza** 2019-02-27 11:56 UTC

**Comment by ferdiga** [comment] 2019-02-27 11:57
thanks, I'll try to find a solution

**Comment by ferdiga** [comment] 2019-03-01 07:35
FYI
- problem is python 3.5.3
- solved in python 3.6.5

**Comment by pedrobaeza** [comment] 2019-03-01 09:13
OK, good to know, although I haven't found that one and we are using officially supported Python version, which is Python 3.5.

**Comment by ferdiga** [comment] 2019-03-01 09:21
probably I have to change the mail provider :-(

**Comment by pedrobaeza** [comment] 2019-03-01 09:24
We are using https://www.mailgun.com/ in combination with https://github.com/OCA/social/tree/11.0/mail_tracking_mailgun
