### ISSUE TITLE
uninstalling modules and reinstalling causes duplicates sequences

### ISSUE THREAD

**Issue by sciallo** [OCA/OCB#897] opened 2019-12-22 18:53 UTC
Impacted versions: 12

Steps to reproduce: Uninstall sales and reinstall

Current behavior: Settings->technical->sequences shows duplicates of sequences

Expected behavior: I would think uninstalling should remove sequences and reinstalling should recreate it (? please correct me if I'm wrong)

Video/Screenshot link (optional):
![Screenshot_20191222_134748](https://user-images.githubusercontent.com/17577898/71325961-4fd78080-24c2-11ea-956d-59c12efb13fd.png)

**Comment by pedrobaeza** [comment] 2019-12-23 11:32
This is the repository OCB, which means that only bug reports that affect this specific version should be logged here.

Any way, I can tell you that this is not a bug, as it's the expected behavior on that way of doing things, as they are noupdate=1 records. If you do such uninstall/install thing, you must adjust things accordingly your preferences (keep old record, put new one...).

Closing as such.

**Closed as completed by pedrobaeza** 2019-12-23 11:32 UTC
